### PR TITLE
T9016: fix MSCHAPv1 and v2

### PR DESCRIPTION
**Pull request by hedrok**
## Change summary

MD4 requires legacy openssl provider:
https://docs.openssl.org/3.0/man7/OSSL_PROVIDER-legacy/

Load the provider in mschap_v1 and mschap_v2 modules to make them work.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T9016

## How to test / Smoketest result

As described in the task:

Server config:

set service pppoe-server interface eth1
set service pppoe-server gateway-address '192.0.2.1'
set service pppoe-server client-ip-pool RV-POOL range '192.0.2.100-192.0.2.110'
set service pppoe-server default-pool 'RV-POOL'
set service pppoe-server authentication mode 'local'
set service pppoe-server authentication local-users username test password 'test'
set service pppoe-server authentication protocols 'mschap-v2'

Client config:

set interfaces pppoe pppoe0 source-interface 'eth1'
set interfaces pppoe pppoe0 no-default-route
set interfaces pppoe pppoe0 authentication username 'test'
set interfaces pppoe pppoe0 authentication password 'test'

Before PR: authentication failure, after PR: works.

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by hedrok** [comment]
I have read the CLA Document and I hereby sign the CLA.

File: accel-pppd/auth/auth_mschap_v1.c [hunk 1]
```diff
@@ -10,6 +10,7 @@
 
 #include <openssl/des.h>
 #include <openssl/evp.h>
+#include <openssl/provider.h>
```
[the remark this answers is not in the document]
Comment (dmbaturin) [reply accel-pppd/auth/auth_mschap_v1.c:13]: There is no harm in adding include guards and I think we may want to keep it buildable with older OpenSSL if we want accel-ppp-ng to support RHEL8 and other distros with a long support cycle that are still in use.

File: accel-pppd/auth/auth_mschap_v1.c [hunk 2]
```diff
@@ -119,6 +123,9 @@ static void auth_data_free(struct ppp_t *ppp, struct auth_data_t *auth)
 		triton_timer_del(&d->interval);
 
 	_free(d);
+
+	OSSL_PROVIDER_unload(ossl_legacy_provider);
+	ossl_legacy_provider = NULL;
 }
```
[the remark this answers is not in the document]
Comment (dmbaturin) [reply accel-pppd/auth/auth_mschap_v1.c:129]: As I understand, the legacy provider library only has functions and no mutable data. What is the reason to unload it rather than keep the same instance as long as the process is running?

File: accel-pppd/auth/auth_mschap_v1.c [hunk 3]
```diff
@@ -105,6 +107,8 @@ static struct auth_data_t* auth_data_init(struct ppp_t *ppp)
 	d->auth.len = 1;
 	d->ppp = ppp;
 
+	ossl_legacy_provider = OSSL_PROVIDER_load(NULL, "legacy");
```
Comment (ritika0313) [inline accel-pppd/auth/auth_mschap_v1.c:110]: With the earlier patch that I shared, it worked but @alexk37 found the below concern regarding the runtime policy override. I think that concern still holds with this patch as well.
Finding from the previous patch by Alex:
_"The patch loads default+legacy programmatically into the process libctx, ignoring the system openssl.cnf provider policy. On a host locked to a FIPS-only provider set, accel-pppd would now have non-FIPS providers injected."_

File: accel-pppd/auth/auth_mschap_v1.c [hunk 4]
```diff
@@ -105,6 +107,8 @@ static struct auth_data_t* auth_data_init(struct ppp_t *ppp)
...
+
```
Comment (ritika0313) [inline accel-pppd/auth/auth_mschap_v1.c:111]: We also might want to load the default provider for SHA-1, AES, etc.
Loading legacy without default might lead to loss in access to these algorithms from the default provider.

**Review by ritika0313 — CHANGES_REQUESTED** [review]
The current code changes have some lifecycle issues and missing default provider loading.
The patch I shared earlier had a different architecture and avoided the lifecycle issues.
So, If it looks ok to @hedrok, some changes can be made on top of that patch to address @alex37 's concern. 
For that, may be we can introduce a config option in accel-ppp config to let the admin make a conscious decision to override the policy and load legacy provider in order to fetch the legacy algorithms.

_(Other option would be to use a dedicated OpenSSL libctx only for MS-CHAP, load legacy there, fetch MD4/DES from that libctx. But that would be a major refactor and add a lot of complexity - riskier for this stage. So I do not suggest that.)_

Below are the code changes suggested earlier by me for reference:
```
diff --git a/accel-pppd/main.c b/accel-pppd/main.c
index dcbbc0a..e2cf818 100644
--- a/accel-pppd/main.c
+++ b/accel-pppd/main.c
@@ -17,6 +17,9 @@
 #include <sys/resource.h>
 
 #include <openssl/ssl.h>
+#if OPENSSL_VERSION_NUMBER >= 0x30000000L
+#include <openssl/provider.h>
+#endif
 
 #include "triton/triton.h"
 
@@ -41,6 +44,11 @@ static int term;
 static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;
 static pthread_cond_t cond = PTHREAD_COND_INITIALIZER;
 
+#if OPENSSL_VERSION_NUMBER >= 0x30000000L
+static OSSL_PROVIDER *openssl_provider_default;
+static OSSL_PROVIDER *openssl_provider_legacy;
+#endif
+
 #if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
 static pthread_mutex_t *ssl_lock_cs;
 
@@ -78,6 +86,16 @@ static void openssl_init(void)
 	OpenSSL_add_all_algorithms();
 	OpenSSL_add_all_digests();
 
+#if OPENSSL_VERSION_NUMBER >= 0x30000000L
+	openssl_provider_default = OSSL_PROVIDER_load(NULL, "default");
+	if (!openssl_provider_default)
+		log_error("main: failed to load OpenSSL provider 'default'\n");
+
+	openssl_provider_legacy = OSSL_PROVIDER_load(NULL, "legacy");
+	if (!openssl_provider_legacy)
+		log_error("main: failed to load OpenSSL provider 'legacy'\n");
+#endif
+
 #if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
 	ssl_lock_init();
 #endif
@@ -450,6 +468,17 @@ int main(int _argc, char **_argv)
 
 	triton_terminate();
 
+#if OPENSSL_VERSION_NUMBER >= 0x30000000L
+	if (openssl_provider_legacy) {
+		OSSL_PROVIDER_unload(openssl_provider_legacy);
+		openssl_provider_legacy = NULL;
+	}
+	if (openssl_provider_default) {
+		OSSL_PROVIDER_unload(openssl_provider_default);
+		openssl_provider_default = NULL;
+	}
+#endif
+
 	if (restart != -1)
 		__core_restart(restart);
```

File: accel-pppd/auth/auth_mschap_v1.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (hedrok) [reply accel-pppd/auth/auth_mschap_v1.c:13]: I'll add guards, that is not a problem, but though currently the package builds with openssl 1.1.1, I am pretty sure it will fail on start:

```
/home/vyos/tasks/VD-4576-accel-ppp-md4/vyos-build/scripts/package-build/linux-kernel/accel-ppp-ng/accel-pppd/extra/chap-secrets.c: In function ‘parse_hash_chain’:
/home/vyos/tasks/VD-4576-accel-ppp-md4/vyos-build/scripts/package-build/linux-kernel/accel-ppp-ng/accel-pppd/extra/chap-secrets.c:751:26: warning: implicit declaration of function ‘EVP_MD_fetch’; did you mean ‘EVP_MD_flags’? [-Wimplicit-function-declaration]
  751 |                 hc->md = EVP_MD_fetch(NULL, ptr1, NULL);
      |                          ^~~~~~~~~~~~
      |                          EVP_MD_flags
/home/vyos/tasks/VD-4576-accel-ppp-md4/vyos-build/scripts/package-build/linux-kernel/accel-ppp-ng/accel-pppd/extra/chap-secrets.c:751:24: warning: assignment to ‘const EVP_MD *’ {aka ‘const struct evp_md_st *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  751 |                 hc->md = EVP_MD_fetch(NULL, ptr1, NULL);
      |                        ^

```

`EVP_MD_fetch` is not defined in OpenSSL 1.1.1 unlike OpenSSL 3.0, so as soon as the process tries to start, it will fail with undefined symbol.

So if we want to support older OpenSSL releases, we need to create separate task to test  and fix it and I think we need to add some CI to make it checked with each PR, or I'm pretty sure it will fail over time.

**Comment by hedrok** [comment]
@ritika0313 Your patch seems to fully resolve issue + has no problems of my PR that were found by you nad AI.
Also @dmbaturin confirmed that we are not FIPS-compatible now and Alex's concern about FIPS-compatibility though valid, but not relevant yet.
I'm closing my PR and suggest you create PR from your patch - I'll review it quickly.
